alternate: 鸿蒙应用开发Harmonys

sidebar:
  position: left
  avatar: avatar.jpg

menu:
  home: / || home
  about: 
    default: / || user
    aboutsite: /about/ || user

reward:
  enable: true
  account:
    avatar: /avatar.jpg